import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="${styles.container}">
      <Head>
        <title>Town of Lieto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Town of Lieto
        </h1>

        <p className={styles.description}>
          Multiplayer social game
        </p>

        <div className={styles.grid}>
          <a href="/play" className={styles.card}>
            <h2>Play &rarr;</h2>
            <p>Queue into a game right now!</p>
          </a>

          <a href="/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn how to play Town of Lieto?</p>
          </a>

          <a
            href="/account"
            className={styles.card}
          >
            <h2>Account &rarr;</h2>
            <p>See your account information like stats and achievements.</p>
          </a>

          <a
            href="/news"
            className={styles.card}
          >
            <h2>News &rarr;</h2>
            <p>
             Follow Town of Lieto updates and keep up to date with new features.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
